# Generated by Django 4.0.4 on 2022-05-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=150)),
                ('full_url', models.CharField(max_length=999999)),
                ('click_counts', models.IntegerField(default=0)),
            ],
        ),
    ]
