# Generated by Django 4.0.4 on 2022-06-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortner',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urlshortner',
            name='is_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='urlshortner',
            name='full_url',
            field=models.CharField(blank=True, max_length=999999, null=True),
        ),
    ]
