# Generated by Django 4.0.4 on 2022-05-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_discord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_level',
            field=models.IntegerField(default=0),
        ),
    ]
