# Generated by Django 4.0.4 on 2022-05-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_current_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_public_organization',
            field=models.BooleanField(default=False),
        ),
    ]
