# Generated by Django 4.0.4 on 2022-05-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_public_name',
            field=models.BooleanField(default=False),
        ),
    ]
