# Generated by Django 4.0.4 on 2022-05-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_is_public_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banned_reason',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
