# Generated by Django 4.0.4 on 2022-05-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_options_profile_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ip_address',
            field=models.JSONField(default='[""]'),
        ),
    ]
