# Generated by Django 4.0.4 on 2022-06-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ips',
            options={'verbose_name_plural': 'IP addresses'},
        ),
        migrations.AddField(
            model_name='profile',
            name='ip_address_count',
            field=models.IntegerField(default=0),
        ),
    ]
