# Generated by Django 4.0.4 on 2022-06-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_ips_options_profile_ip_address_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.CharField(default='https://avatars.dicebear.com/api/pixel-art-neutral/helooooooooooo.svg', max_length=150),
        ),
    ]
