# Generated by Django 4.0.4 on 2022-07-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_completed_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
