# Generated by Django 4.0.4 on 2022-08-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_profile_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stats',
            field=models.JSONField(default=dict),
        ),
    ]
