# Generated by Django 4.0.4 on 2022-06-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0003_rename_unique_name_question_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
