# Generated by Django 4.0.4 on 2022-06-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0004_question_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='score',
            new_name='points',
        ),
    ]
