# Generated by Django 4.0.4 on 2022-08-18 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hunt', '0007_samplequestion_completed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='EasterEgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egg', models.TextField()),
                ('points', models.IntegerField(default=0)),
                ('claimed', models.BooleanField(default=False)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Easter Eggs',
            },
        ),
    ]
